[env]

[tools]
argocd = "2.13.3"
aws-cli = "2.28.11"
cilium-cli = { version = "0.18.6", exe = "cilium" }
cilium-hubble = "1.18.0"
crane = "0.20.6"
fd = "10.2.0"
fzf = "0.65.1"
github-cli = "2.76.2"
go = "1.25.0"
golangci-lint = "2.4.0"
helm = "3.18.5"
k9s = "0.50.9"
kube-linter = "0.7.5"
kubectl = "1.33.4"
kubectx = "0.9.5"
kubevela = "1.10.3"
kustomize = "5.7.1"
lazygit = "0.54.2"
mongosh = "2.5.6"
neovim = "0.11.3"
node = "24.6.0"
ripgrep = "14.1.1"
talosctl = { version = "1.10.6", exe = "talosctl" }
vault = "1.20.2"
yamlfmt = "0.17.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
