[env]

[tools]
argocd = "2.13.3"
aws-cli = "2.23.6"
crane = "0.20.3"
fd = "10.2.0"
github-cli = "2.65.0"
helm = "3.17.0"
k9s = "0.32.7"
kube-linter = "0.7.1"
kubecolor = "0.0.25"
kubectl = "1.32.1"
kubectx = "0.9.5"
kubevela = "1.9.13"
kustomize = "5.6.0"
lazygit = "0.45.2"
mongosh = "2.3.8"
neovim = "0.10.3"
node = "23.6.1"
ripgrep = "14.1.1"
talosctl = "1.9.2"
vault = "1.18.3"
yamlfmt = "0.15.0"
